// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8aRI5urJ4v4z342576LVsKcsDjfasdsA',
    appId: '1:994028747843:web:a1564103093adaa87fa8f6',
    messagingSenderId: '994028747843',
    projectId: 'le-pondy-kitchen',
    authDomain: 'le-pondy-kitchen.firebaseapp.com',
    storageBucket: 'le-pondy-kitchen.firebasestorage.app',
    measurementId: 'G-5XQ8LNHV9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-26rBvakFRiChuFcEEAlq-QbghnQEqI',
    appId: '1:994028747843:android:5ab8a34c9ff29bf77fa8f6',
    messagingSenderId: '994028747843',
    projectId: 'le-pondy-kitchen',
    storageBucket: 'le-pondy-kitchen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK8hxbjZSoPS0Ol_1c8RsMR4xj7n1s7UU',
    appId: '1:994028747843:ios:5696d9190597a98d7fa8f6',
    messagingSenderId: '994028747843',
    projectId: 'le-pondy-kitchen',
    storageBucket: 'le-pondy-kitchen.firebasestorage.app',
    iosBundleId: 'com.example.faceIdLogin',
  );
}
